In [3]:
import numpy as np
a=np.arange(4)
print(a)
b=a
c=a
d=b
a[0]=10
print(a)
b is a
d is a

[0 1 2 3]
[10  1  2  3]


True

In [6]:
b=a.copy() #deep copy,把a的值赋给b,但a,b不关联
a[2]=44
print(a)
print(b)

[10  1 44  3]
[10  1 44  3]
