In [2]:
import numpy as np
a=np.array([10,20,30,40])
b=np.arange(4)
print(a,b)
c=a-b #矩阵减法
print(c)

[10 20 30 40] [0 1 2 3]
[10 19 28 37]


In [2]:
c=a+b #矩阵加法
print(c)

[10 21 32 43]


In [3]:
c=b**2 #在Python中平方、次方用**
print(c)

[0 1 4 9]


In [4]:
c=10*np.sin(a) #三角函数，通过调用numpy中的函数
print(c)

[-5.44021111  9.12945251 -9.88031624  7.4511316 ]


In [6]:
print(b)
print(b<3) #判断b中哪些值是小于3的，返回元素为布尔型的列表

[0 1 2 3]
[ True  True  True False]


In [7]:
a=np.array([[1,1],[0,1]])
b=np.arange(4).reshape((2,2))
print(a)
print(b)

[[1 1]
 [0 1]]
[[0 1]
 [2 3]]


In [9]:
c=a*b #逐位相乘
print(c)

c_dot=np.dot(a,b)
c_dot1=a.dot(b)
print(c_dot) #矩阵相乘
print(c_dot1) #另一种写法

[[0 1]
 [0 3]]
[[2 4]
 [2 3]]
[[2 4]
 [2 3]]


In [13]:
a=np.random.random((2,4)) #随机创建一个2行4列的矩阵
print(a)
print(np.sum(a)) #矩阵所有元素之和
print(np.min(a)) #矩阵最小元素
print(np.max(a)) #矩阵最大元素

print(np.sum(a,axis=1)) #axis表示维度，axis=1对行求和
print(np.sum(a,axis=0)) #axis=0对列求和
#关于axis这个属性的定义是基于数组.shape 的这个属性,
#它是一个Python元组,对于二维数组而言,axis=0表示这个元组的第一个元素,axis=1表示第二个元素.
#假如这个数组是三维数组,axis=0代表的是第一个维度也就是页,axis=1,表示的是行,axis=2表示列

[[0.03021769 0.2205137  0.71329625 0.13152101]
 [0.24729601 0.37339794 0.16424974 0.1769258 ]]
2.057418144568723
0.03021768837981753
0.7132962510835831
[1.09554865 0.9618695 ]
[0.2775137  0.59391164 0.877546   0.30844681]


In [29]:
A=np.arange(2,14).reshape((3,4))
print(A)
print(np.argmin(A)) #搜索最小值的索引
print(np.argmax(A)) #搜索最大值的索引
print(np.mean(A)) #矩阵平均值
print(A.mean()) #矩阵平均值另一种方法
print(np.average(A)) #矩阵加权平均值，尽量用mean()
print(np.median(A)) #矩阵中位数
print(np.cumsum(A)) #累加，结果元素个数与A相同，第二个数是A前两个值想加，第k个数是A前k个数相加
print(np.diff(A)) #累差，A是3*4，累差结果为3*3，相邻两个数之间的差

print(np.nonzero(A)) #返回非零数的索引，第一个array表示行,第二个array表示列

print(np.sort(A)) #矩阵逐行排序

print(np.transpose(A)) #矩阵转置
print(A.T) #矩阵转置另一种方法
print((A.T).dot(A)) #矩阵乘法示例

print(np.clip(A,5,9)) #滤波，在A中，比5小的数都变成5，比9大的数都变成9，5-9的数保留

print(np.mean(A,axis=0)) #axis=0对列求均值
print(np.mean(A,axis=1)) #axis=1对行求均值


[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
0
11
7.5
7.5
7.5
7.5
[ 2  5  9 14 20 27 35 44 54 65 77 90]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]
[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]
[[140 158 176 194]
 [158 179 200 221]
 [176 200 224 248]
 [194 221 248 275]]
[[5 5 5 5]
 [6 7 8 9]
 [9 9 9 9]]
[6. 7. 8. 9.]
[ 3.5  7.5 11.5]
