In [9]:
import numpy as np

A=np.array([1,1,1])
B=np.array([2,2,2])

print(np.vstack((A,B))) #上下合并 vertical垂直合并

print(np.hstack((A,B))) #左右合并 horizontal水平合并

print(A.T) #定义的是数组,不是矩阵，转置不了
print(A[np.newaxis,:]) #给数组A添加维度，此时变成了一维矩阵1*3：向量
print(A[:,np.newaxis]) #变成了3*1的矩阵

[[1 1 1]
 [2 2 2]]
[1 1 1 2 2 2]
[1 1 1]
[[1 1 1]]
[[1]
 [1]
 [1]]


In [14]:
#先将array添加维度，不然没有axis=1这个维度
A=np.array([1,1,1])[:,np.newaxis]
B=np.array([2,2,2])[:,np.newaxis]

C=np.concatenate((A,B,B,A),axis=0) #多个array合并，同时可指定哪个方向上
#axis=0,对行操作（增加行），垂直合并
#axis=1,对列操作（增加列），水平合并
print(C)

[[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]]
