In [3]:
import numpy as np
A=np.arange(3,15) #一维array
print(A)
print(A[3])

[ 3  4  5  6  7  8  9 10 11 12 13 14]
6


In [11]:
A=np.arange(3,15).reshape((3,4)) #二维array
print(A)
print(A[2])
print(A[0][3])
print(A[0,3])
 #用冒号：代替该行（列）所有的数
print(A[2,:])
print(A[:,1])
print(A[1,1:3]) #输出A[1][1],A[1][2]

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[11 12 13 14]
6
6
[11 12 13 14]
[ 4  8 12]
[8 9]


In [14]:
for row in A: #迭代每一行
    print(row)

for column in A.T: #迭代每一列
    print(column)

print(A.flatten()) #A.flat()返回的是一个object
for item in A.flat: #迭代每一项
    print(item)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]
[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14
