In [1]:
import numpy as np

a=np.array([2,23,4]) #array元素之间用空格隔开
print(a) #array元素之间用空格隔开，和列表不同（用逗号隔开）

[ 2 23  4]


In [6]:
 #可在创建时定义array的type（整数型，浮点型等）
a1=np.array([2,3,4],dtype=np.int) #整数型 np.int64
print(a1.dtype)

a2=np.array([2,3,4],dtype=np.float) #浮点型 np.float32
print(a2.dtype)

int32
float64


In [7]:
#定义矩阵
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [17]:
#定义特殊矩阵
a=np.zeros((3,4)) #定义三行四列的零矩阵
print(a)

b=np.ones((2,3),dtype=np.int16) #定义2行3列的单位矩阵
print(b)

c=np.empty((3,4)) #定义空矩阵
print(c)

d=np.arange(10,20,2) #生成有序矩阵：起始值是10，终止值是20（不等于20），步长是2
print(d)
d2=np.arange(12).reshape((3,4)) #生成从0到11的3行4列矩阵
print(d2)

#生成线段
e=np.linspace(1,10,5) #从1到10生成5段的数列
print(e)
e2=np.linspace(1,10,6).reshape((2,3)) #更改形状：2行3列矩阵
print(e2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 1 1]
 [1 1 1]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[10 12 14 16 18]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 1.    3.25  5.5   7.75 10.  ]
[[ 1.   2.8  4.6]
 [ 6.4  8.2 10. ]]
